# -*- coding: utf-8 -*-
# @Author: rjezequel
# @Date:   2019-12-20 09:18:14
# @Last Modified by:   ronanjs
# @Last Modified time: 2020-01-13 15:45:28

- 
  name: Create session
  stc: 
    action: session
    user: ansible
    name: stream-mesh

- 
  name: Create 5 base ports
  stc: 
    action: create
    count: 5
    objects: 
      - project: 
          - port: 
              location: "//(Offline)/${item % 8+1}/${math.floor(item/8)+1}"
              name: "Port $item"


-
  name: Create 5 emulated devices - one of each port
  stc: 
    action: create
    under: ref:/project
    count: 5
    objects: 
    - emulateddevice: 
        AffiliatedPort: ref:/port[name=Port $item]
        DeviceCount: 10
        name: "Device $item"
        PrimaryIf: ref:./Ipv4If
        TopLevelIf: ref:./Ipv4If
        EthIIIf: 
          SourceMac: be:ef:00:00:$item:00
        Ipv4If: 
          AddrStep: 0.0.0.2
          Address: 10.0.$item.1
          Gateway: 192.85.1.1
          PrefixLength: 16
          stackedon: ref:./EthIIIf


- 
  name: Configure the traffic generator
  stc: 
    count: 5
    action: create
    under: ref:/project
    objects: 
    - StreamBlock: 
        TrafficPattern: Mesh
        EnableStreamOnlyGeneration: true
        SrcBinding-targets: ref:/EmulatedDevice[name=Device $item]/Ipv4If
        DstBinding-targets: ref:/EmulatedDevice[name!=Device $item]/Ipv4If
        AffiliationStreamBlockLoadProfile: 
          Load: 100


- 
  name: Start the traffic
  stc: 
    action: perform
    command: GeneratorStart
    properties: 
      GeneratorList: ref:/project 






